# Generated by Django 3.1.3 on 2020-11-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_thumbup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('hdate', models.DateField()),
                ('jobid', models.CharField(max_length=20)),
                ('salarys', models.IntegerField()),
                ('commpct', models.FloatField()),
                ('mgrid', models.IntegerField()),
                ('deptid', models.IntegerField()),
            ],
        ),
    ]
